build:
  os: ubuntu-24.04
  tools:
    # python: "mambaforge-latest"
    # python: "3.11"
    python: "3.11"
  apt-packages:
    - doxygen
    - graphviz

sphinx:
  configuration: source/conf.py

python:
  install:
  - requirements: requirements.txt